version: '3.8'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
    volumes:
      - .:/app

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
